### ISSUE TITLE
导入route后依然显示@route Invalid or unexpected token

### ISSUE THREAD

**Issue by MadaoMkII** [zhang740/egg-controller#13]
![image](https://user-images.githubusercontent.com/33247241/61576618-bb31b680-ab0e-11e9-839c-610d9ba9bd52.png)
用的文档里的最小可实现测试用例， 在最开始已经 导入const route = require("egg-controller");求助如何正确使用

**Comment by zhang740** [comment]
route 不是默认导出 `const { route } = xxx` 推荐用 TypeScript，这种问题类型系统都会有提示
