### ISSUE TITLE
当使用[function]作为被修饰方法的名称时报错

### ISSUE THREAD

**Issue by JKJKJKQ** [zhang740/egg-controller#14]
当使用@route作为修饰符，此时被修饰的方法名称显得无用
我尝试使用以下写法,egg-controller报了几个错误，但是我修改源文件后，在egg框架下是可以正常运行的。是否可以兼容这种写法
以下是我的写法：
`@route('post /test')
  private async [Symbol()]() {
    return
  }`

**Comment by zhang740** [comment]
方法名还是有一定作用的，比如：生成前端对应调用方法，出错堆栈等，方法名可以表明含义，比如路由路径可以根据方法名生成
