### ISSUE TITLE
Invalid or unexpected token 是否可以指导一下

### ISSUE THREAD

**Issue by wadecha** [zhang740/egg-controller#16]
![image](https://user-images.githubusercontent.com/10524259/70857479-1b941b00-1f2a-11ea-85a4-9879e8c6b1b9.png)

已经 用 const { route } = require('egg-controller'); 导入了，网上资料太少了，一直找不到原因，是否可以指导一下

**Comment by wadecha** [comment]
@zhang740   是否有看到

**Comment by zhang740** [comment]
@wadecha 你这个是 ts 么？或者支持 decorator 的 es 环境？

**Comment by wadecha** [comment]
我是 egg.js，阿里的nodejs 框架用的，不是 ts

**Comment by zhang740** [comment]
@wadecha egg.js 是框架，也支持 ts 来写，你这个是开发环境不支持 decorator 特性，要么对 es 编译，要么改用 ts 来开发 https://eggjs.org/zh-cn/tutorials/typescript.html
