### ISSUE TITLE
这个是必须在 使用 TypeScript 搭建的 Egg 才可以使用吗，直接用 JavaScript的方式，可以使用吗

### ISSUE THREAD

**Issue by xiaoxiunique** [zhang740/egg-controller#18]
我们的项目中没有使用到 TypeScript，是不是就不能使用这个库啊

**Comment by zhang740** [comment]
可以的，但支持有限，最简单的方式，将 js 后缀改为 ts，关闭 TypeScript 的部分校验，就可以最低成本使用 TypeScript 的一些特性，eggjs 也有相应的文档 https://eggjs.org/zh-cn/tutorials/typescript.html
