### ISSUE TITLE
我想请问如何在后端根据controller的注解导出比如{routerPath:routerName}这样的对象

### ISSUE THREAD

**Issue by bymmry** [zhang740/egg-controller#4]
根据您插件的写法

```
...
@route('/api/test/create', { name: '创建test', method: ['post'] })
 async create() {
   return await this.ctx.service.test.create();
 }
...
```

想得到如下的对象
```
...
result = [{
  '/api/test/create': {
    name:'创建test',
    method: 'post',
  },
}]
...
```

目前比较小白，很多不懂，不知道有什么方法可以实现我这个想法。主要是想把controller写的路由全部导出到一个文件里，方便看有多少接口，我现在用ctx.app.controller.test拿到的东西，看得不是很懂，不知道怎么获取到注解写的信息。

目前刚刚接触这个框架，看到您的插件，眼前一亮，如果可以给点思路，感激不尽！

**Comment by zhang740** [comment]
@bymmry 本插件默认会输出路由信息，会在启动后写入 `run/route_map.json` 文件，而且会输出 OpenAPI 3.0 格式数据到 `run/openapi_3.json`，你可以查看下这两个文件，如果想要自己做处理，可以通过暴露的API，`getControllers/getRoutes` 方法获取到收集的路由，不过需要注意调用时机

**Comment by bymmry** [comment]
非常感谢🙏，可以了
