### ISSUE TITLE
@controller不起作用

### ISSUE THREAD

**Issue by shaoxiong789** [zhang740/egg-controller#9]
@controller 配置 的前缀路径不起作用，浏览器要忽略@controller 路径才能访问

**Comment by zhang740** [comment]
看下你 @route 设置的路由是什么？ 如果是 `/xxx` 开头，那么会忽略 @controller 中的前缀，可以 `xxx` 去掉 / 试下

**Comment by shaoxiong789** [comment]
好的，谢谢
